# Generated by Django 5.1.4 on 2024-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
