# Generated by Django 5.1 on 2024-12-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
