# Generated by Django 5.1.2 on 2024-12-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
