# Generated by Django 5.1.2 on 2024-12-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0002_servicelist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelist',
            name='a_status',
            field=models.CharField(default='Not Arrived ', max_length=10),
        ),
    ]
