# Generated by Django 5.1.2 on 2024-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0003_servicelist_a_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='a_status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
