# Generated by Django 5.1.2 on 2024-12-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0004_alter_servicelist_a_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
