# Generated by Django 5.1.2 on 2024-12-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0006_remove_service_created_at_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='insertservice'),
        ),
    ]
