# Generated by Django 5.1.2 on 2024-12-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0008_kowshiq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kowshiq',
        ),
        migrations.AddField(
            model_name='service',
            name='learn',
            field=models.URLField(default='https://example.com', max_length=250),
        ),
    ]
