# Generated by Django 5.1.2 on 2024-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carservice', '0011_alter_service_learn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='learn',
            field=models.URLField(default='https://example.com'),
        ),
    ]
